# Generated by Django 5.0.6 on 2024-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restorant_logo/'),
        ),
        migrations.AlterField(
            model_name='restorant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
