# Generated by Django 5.0.6 on 2024-06-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscribers_subscriptionbuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
