# Generated by Django 5.0.6 on 2024-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_restorant_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('subscription_time', models.DateTimeField(blank=True, null=True)),
                ('useg_limit', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionbuyer',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
