# Generated by Django 5.0.6 on 2024-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscription_code_subscriptionbuyer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_code',
            name='type_of_subscription',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionbuyer',
            name='type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
