# Generated by Django 5.0.6 on 2024-06-14 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subscription_code_type_of_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionbuyer',
            name='subscription_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 18, 51, 42, 330046, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
