# Generated by Django 5.0.6 on 2024-06-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subscriptionbuyer_subscription_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionbuyer',
            name='subscription_start_time',
            field=models.DateTimeField(),
        ),
    ]
