# Generated by Django 5.0.6 on 2024-05-23 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restorant',
            name='manager_restorant',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='manager_restorant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restorant',
            name='staffs',
            field=models.ManyToManyField(
                blank=True, related_name='staffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
