# Generated by Django 5.0.6 on 2024-05-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_restorant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='numebr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
