# Generated by Django 5.0.6 on 2024-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_service_blockip_key_blockip_user_order_order_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetable',
            name='ocupied',
            field=models.IntegerField(default=0),
        ),
    ]
