# Generated by Django 5.0.6 on 2024-05-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_restorant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
