# Generated by Django 5.0.6 on 2024-06-19 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_service_aprox_time_max_service_aprox_time_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceshop',
            name='manager_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_service', to=settings.AUTH_USER_MODEL),
        ),
    ]
