# Generated by Django 5.0.6 on 2024-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_order_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
