# Generated by Django 5.0.6 on 2024-06-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_serviceshop_manager_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorant',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorant',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceshop',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
