# Generated by Django 5.0.6 on 2024-06-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
