# Generated by Django 5.0.6 on 2024-06-01 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_order_completed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='completed_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
