# Generated by Django 5.0.6 on 2024-06-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restorant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.restorant'),
            preserve_default=False,
        ),
    ]
