# Generated by Django 5.0.6 on 2024-06-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_meal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorder',
            name='meal_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.mealitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealorder',
            name='unlimited',
            field=models.BooleanField(default=True),
        ),
    ]
