# Generated by Django 5.0.6 on 2024-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_mealorder_meal_item_mealorder_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='mealItems',
            field=models.ManyToManyField(to='app.mealitem'),
        ),
    ]
