# Generated by Django 5.0.6 on 2024-06-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_meal_mealitems_remove_mealorder_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealorder',
            name='total',
        ),
    ]
